const SATSPERBITCOIN = 100000000;

const LIQUIDAMOUTBUFFER = 0; //sats
const LIGHTNINGAMOUNTBUFFER = 0; //sats
const DUST_LIMIT_FOR_BTC_CHAIN_PAYMENTS = 546;
const DUST_LIMIT_FOR_LBTC_CHAIN_PAYMENTS = 21;

const SPARK_TO_LN_FEE = 0.0025;
const LN_TO_SPARK_FEE = 0.0015;
const SPARK_TO_SPARK_FEE = 0;

const BLITZ_FEE_SATS = 4;
const BLITZ_FEE_PERCET = 0.004;

export {
  SATSPERBITCOIN,
  LIQUIDAMOUTBUFFER,
  LIGHTNINGAMOUNTBUFFER,
  DUST_LIMIT_FOR_BTC_CHAIN_PAYMENTS,
  DUST_LIMIT_FOR_LBTC_CHAIN_PAYMENTS,
  SPARK_TO_LN_FEE,
  LN_TO_SPARK_FEE,
  SPARK_TO_SPARK_FEE,
  BLITZ_FEE_SATS,
  BLITZ_FEE_PERCET,
};
